# Generated by Django 6.0.6 on 2026-06-26 15:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobado', 'Aprobado'), ('Devuelto', 'Devuelto')], default='Pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha_alquiler',
            field=models.DateField(default=datetime.date(2026, 6, 26)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha_devolucion',
            field=models.DateField(default=datetime.date(2026, 6, 26)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(default=datetime.date(2026, 6, 26)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='estado',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('Alquilado', 'Alquilado'), ('Mantenimiento', 'Mantenimiento')], default='Disponible', max_length=20),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(default=1),
        ),
    ]
